### ISSUE TITLE
slight modification to map multiple mask PNG files to a single image file

### ISSUE THREAD

**Issue by cpoptic** [HasnainRaz/SemSegPipeline#6]
Great tool Hasnain, thank you for this!

This works if you have a 1:1 ratio of images to masks (i.e. one image file with one corresponding mask file).

What if your data is structured with more than one mask file (each mask file containing a single mask) for each image file (one mask.png file for each mask polygon shape)?

For example, say you have 3 masks on, say, image # 17.  So your image file name is image_17.jpg.  

Your mask files are:
mask_17_0.png
mask_17_1.png
mask_17_2.png

How would you modify this script to accept a list of mask files rather than a single mask file.

# Where image_paths[0] = 'data/training/images/image_0.png' 
# And mask_paths[0] = ['data/training/masks/mask_0_0.png',
'data/training/masks/mask_0_1.png',
'data/training/masks/mask_0_2.png',]

**Comment by HasnainRaz** [comment]
you could have: 
image_paths = [image_0.png, image_1.png] and
mask_paths = [[mask_0_0.png, mask_0_1.png, mask_0_2.png],[mask_1_0.png, mask_1_1.png]] 

Then you would need to swap out the parse function for your own function:
```python
import cv2 # Optionally you could use PIL
import numpy as np

def _parse_data(self, image_path, mask_path_list):
    image = cv2.imread(image_path, 1)
    masks = []
    for path in mask_path_list:
        masks.append(cv2.imread(path), 0)

   # decide how you want to combine all the masks? here we just stack them across channels
   masks = np.stack(masks, axis=2)

   return image, masks
```

and inside the data batch function you would have:
```python
dataset.map(lambda image, mask: tuple(tf.py_func(
        _parse_data, [image, mask], [tf.uint8, tf.uint8])), num_parallel_calls=num_threads).prefetch(buffer)
```

instead of the current:
```python
data = data.map(self._parse_data, num_parallel_calls=num_threads).prefetch(buffer)
```

This code is untested, so there will probably be bugs you will have to resolve. But hopefully this gives you an idea on how to proceed.
