### ISSUE TITLE
Problem with image size and pairing image with mask

### ISSUE THREAD

**Issue by anilsathyan7** [HasnainRaz/SemSegPipeline#9]
It looks like image_size is supposed to be single number according to code; even though documentation mentions  them as  tuples. So it seems to throw error when i run it unmodified.

Also in python3.6 the os.listdir() function for getting file names may result in different order of image names and may lead to improper pairing of the image with mask. I got improper image-mask pair  from dataset (using 'example-use' code) when i used jpg images for source; even though i changed extension in code. I think, it would be better to sort this list to ensure they are properly paired before applying any other operations/shuffling, considering the images are properly named.

**Comment by HasnainRaz** [comment]
@anilsathyan7 Thank you for the information about the image_size variable, it seems you are correct, I will update the docs.

About the example with os.listdir, you are correct. It is upto you to prepare the lists so that each image-mask index corresponds to the same pair. This is why the comment in the docs mention "mask-0 is the mask to image-0". I think I can be more explicit about this. I'll find a way to make it clearer.
